config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root :to => 'home#index'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :passwords     => 'users/passwords'
  }

  get 'teams' => 'teams#index', as: :user_root

  authenticate :user, lambda { |u| u.email == "davekaro@gmail.com" || u.email == "bhandari.sudershan@gmail.com" } do
    mount Sidekiq::Web => '/sidekiq'
  end

  if Rails.env.development? || Rails.env.try_it?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
    get 'try_it_sign_in' => 'try_it#auto_sign_in'
  end

  namespace :admin do
    resources :users, :only => [:index] do
      collection do
        get :test_raven
      end
      member do
        get :become
      end
    end
  end

  resources :teams, :except => [:show] do
    resources :practices do
      member do
        get :availability_email
        get :availabilities
      end
    end
    resources :matches do
      member do
        get :availabilities
        get :availability_email
        get :player_request_email
        get :lineup_email
      end
      collection do
        get :import
        post :perform_import
      end
    end
    # TODO Delete these routes 7 days later
    resources :match_availabilities, :only => [] do
      collection do
        get :set_availability
      end
    end
    # TODO Delete these routes 7 days later
    resources :practice_sessions, :only => [] do
      collection do
        get :set_availability
      end
    end
    resources :responses, :only => [:index] do
      collection do
        get :set_availability
      end
    end
    resources :results, :only => [:index]
    resources :team_members, :only => [:index, :edit, :update, :destroy] do
      collection do
        get 'new', as: :new
        post 'create', as: :create
      end
      member do
        post 'send_welcome_email'
      end
    end
    member do
      post 'send_welcome_email'
    end
  end

  resources :practices, :only => [] do
    resources :responses, :only => [:create, :update]
    member do
      post 'notify'
    end
  end

  resources :matches, :only => [] do
    resources :responses, :only => [] do
      member do
        post :save_availability
        post :save_note
      end
    end
    member do
      post 'notify'
      post 'notify_player_request'
      post 'notify_lineup'
      get 'edit_lineup' => 'match_lineups#edit'
      get 'edit_results' => 'results#edit'
    end
  end

  resource :change_password, :only => [:edit, :update] do
    member do
      get 'send_reset'
    end
  end

  namespace :api do
    post 'postmark/inbound' => 'postmark#inbound'
    post 'postmark/bounce'  => 'postmark#bounce'
  end
end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  include DestroyedAt

  ROLES = %w[captain co-captain member]

  belongs_to :user
  belongs_to :team

  after_create :setup_responses

  def self.welcome_email_unsent
    where(welcome_email_sent_at: nil)
  end

  def self.welcome_email_sent
    where.not(welcome_email_sent_at: nil)
  end

  def captain?
    role == 'captain' || role == 'co-captain'
  end

  def welcome_email_unsent?
    welcome_email_sent_at.nil?
  end

  def welcome_email_sent?
    !!welcome_email_sent_at
  end

  def send_welcome!(from_user_id)
    from_user = User.find(from_user_id)
    if user.never_signed_in?
      WelcomeMailer.delay.new_user_welcome(from:           from_user.name,
                                           reply_to:       from_user.email,
                                           team_member_id: id)
    else
      WelcomeMailer.delay.welcome(from:           from_user.name,
                                  reply_to:       from_user.email,
                                  team_member_id: id)
    end
    welcome_email_sent!
  end

  def welcome_email_sent!
    update!(welcome_email_sent_at: Time.zone.now)
  end

  def setup_responses
    ActsAsTenant.with_tenant(team) do
      team.matches.each do |match|
        match.responses.create!(user_id: user_id)
      end
    end
  end
end

# == Schema Information
#
# Table name: team_members
#
#  id         :integer          not null, primary key
#  team_id    :integer          default(0), not null
#  user_id    :integer          default(0), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  layout 'team'

  def send_welcome_email
    @team_member = TeamMember.find(params[:id])
    authorize @team_member

    @team_member.send_welcome!(current_user.id)
    redirect_to team_team_members_url(current_team), :notice => 'Welcome email sent'
  end

  def new
    authorize current_team

    emails = SimpleTextAreaParser.parse(params[:emails] || "")
    @add_team_members = AddTeamMembers.users_from_emails(current_team, emails)
  end

  def create
    authorize current_team

    @add_team_members = AddTeamMembers.new(params[:add_team_members])
    if @add_team_members.save(current_team)
      redirect_to team_team_members_url(current_team), notice: "Team members added"
    else
      render :action => 'new'
    end
  end

  def index
    @team_members_welcome_email_unsent = current_team.team_members.welcome_email_unsent
    @team_members = current_team.team_members.welcome_email_sent
    @captain = TeamPolicy.new(current_user, current_team).captain?
  end

  def edit
    @team_member = TeamMember.find(params[:id])
    authorize @team_member
  end

  def update
    @team_member = TeamMember.find(params[:id])
    authorize @team_member

    if @team_member.update(permitted_params.team_member)
      redirect_to team_team_members_url(@team_member.team), :notice => 'Team member updated'
    else
      render :edit
    end
  end

  def destroy
    @team_member = TeamMember.find(params[:id])
    authorize @team_member

    DestroysTeamMember.new(@team_member).destroy

    if current_user.id == @team_member.user_id
      redirect_to teams_url, :notice => 'You have removed yourself from the team'
    else
      redirect_to team_team_members_url(@team_member.team), :notice => 'Team member is now removed from the team'
    end
  end
end

app/views/team_members/_team_members.html.erb
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>Responded at <b class="caret"></b></th>
    </tr>
  </thead>
  <tbody>
    <% team_members.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= mail_to user.email %></td>
      <td><%= user.phone_number %></td>
      <td><%= l practice.response_for(user.id).updated_at, :format => :simple %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/team_members/_team_members_index.html.erb
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>Role</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% team_members_index.sort_by { |tm| tm.user.name }.each do |team_member| %>
    <tr>
      <td><%= team_member.user.name %></td>
      <td>
        <% if policy(team_member).send_welcome_email? && team_member.welcome_email_unsent? %>
          <%= link_to 'Send welcome email',
            send_welcome_email_team_team_member_path(current_team, team_member),
            :method => :post,
            :data   => { :confirm => "Send welcome email to #{team_member.user.email} now?" },
            :class  => 'btn btn-xs btn-info' %>
        <% end %>
        <%= mail_to team_member.user.email %>
      </td>
      <td><%= team_member.user.phone_number %></td>
      <td><%= team_member.role.humanize %></td>
      <td>
        <% if policy(team_member).update? %>
          <%= link_to 'Edit', edit_team_team_member_path(current_team, team_member), :class => 'btn btn-xs btn-default' %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/team_members/edit.html.erb
<% subtitle "Edit settings for #{@team_member.user.name} (#{@team_member.role})" %>

<% if policy(current_team).captain? %>
  <%= simple_form_for([current_team, @team_member]) do |f| %>
    <%= f.error_messages %>

    <div class="row">
      <div class="col-md-3">
        <%= f.input :role, collection: TeamMember::ROLES, value_method: :to_s, label_method: :humanize, include_blank: false %>
      </div>
    </div>
    <p class="help-block">
      Captain and Co-captain both have full access to everything. Members can't set lineups or edit matches.
    </p>
    <%= f.submit 'Save settings', :class => 'btn btn-primary' %>
  <% end %>

  <hr>
<% end%>

<div class="row">
  <div class="col-md-12">
    <div class="alert alert-danger">
      <h4>Remove from team</h4>
      <p>This will delete all match and practice availabilities for <%= @team_member.user.name %>.</p>
      <p>You can <strong>NOT</strong> undo this action.</p>
      <p>
        <%= link_to 'Delete team member data and remove from team',
          team_team_member_path(current_team, @team_member),
          :data => { :confirm => 'Are you sure?' },
          :method => :delete,
          :class => 'btn btn-danger' %>
      </p>
    </div>
  </div>
</div>

app/views/team_members/index.html.erb
<% subtitle 'Team' %>

<% if policy(current_team).captain? %>
  <%= link_to('Add players', new_team_team_members_path(current_team), :class => 'btn btn-default') %>
<% end %>

<% if @team_members.present? || @team_members_welcome_email_unsent.present? %>
  <h3>Team members</h3>
<% end %>

<% if @team_members_welcome_email_unsent.present? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      These members have never been sent a welcome email
      <% if policy(current_team).captain? %>
        <%= link_to 'Send welcome email to all of these members',
          send_welcome_email_team_path(current_team),
          :method => :post,
          :data   => { :confirm => "Send welcome email to #{pluralize(@team_members_welcome_email_unsent.size, "member")} now?" },
          :class  => 'btn btn-xs btn-info' %>
       <% end %>
    </div>
    <%= render :partial => "team_members_index", :object => @team_members_welcome_email_unsent %>
  </div>
<% end %>

<% if @team_members.present? %>
  <%= render :partial => "team_members_index", :object => @team_members %>
<% end %>

app/views/team_members/new.html.erb
<h3>Add players</h3>
<% if @add_team_members.users.size == 0 %>
  <div class="alert alert-info">
    <p>Enter one or more email addresses to add players to your team.</p>
    <p>You can review the new player(s) and set their names on the next step.</p>
  </div>

  <%= form_tag new_team_team_members_path(current_team), :method => :get do %>
    <div class="form-group">
      <div class="row">
        <div class="col-md-8">
          <textarea class="form-control" name="emails"></textarea>
          <p class="help-block">Use comma-separated, space-separated, or one email address per line.</p>
        </div>
      </div>
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-default">
        Next
      </button>
    </div>
  <% end %>
<% else %>
  <%= simple_form_for(@add_team_members, url: create_team_team_members_path, html: { class: "form-inline" }) do |f| %>
    <%= f.error_messages %>
      <div class="alert alert-info">
        <p>Add or modify a name for each player (optional).</p>
        <p>Players with a Breakpoint App account are not editable and will be marked with an <span class="label label-info">existing account</span> label.</p>
      </div>
      <ul class="list-group">
        <%= f.simple_fields_for :users do |user_form| %>
          <li class="list-group-item">
            <%= user_form.input :name,
              input_html: { style: "width: 200px;" },
              label_html: { class: "sr-only" },
              disabled: !user_form.object.new_record?,
              placeholder: "Name" %>
            <% unless user_form.object.new_record? %>
              <span class="label label-info">existing account</span>
            <% end %>
            <%= user_form.object.email %>
            <%= user_form.hidden_field :email%>
          </li>
        <% end %>
      </ul>

    <%= f.submit "Add players to team", class: "btn btn-primary" %>
  <% end %>
<% end %>