config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root :to => 'home#index'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :passwords     => 'users/passwords'
  }

  get 'teams' => 'teams#index', as: :user_root

  authenticate :user, lambda { |u| u.email == "davekaro@gmail.com" || u.email == "bhandari.sudershan@gmail.com" } do
    mount Sidekiq::Web => '/sidekiq'
  end

  if Rails.env.development? || Rails.env.try_it?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
    get 'try_it_sign_in' => 'try_it#auto_sign_in'
  end

  namespace :admin do
    resources :users, :only => [:index] do
      collection do
        get :test_raven
      end
      member do
        get :become
      end
    end
  end

  resources :teams, :except => [:show] do
    resources :practices do
      member do
        get :availability_email
        get :availabilities
      end
    end
    resources :matches do
      member do
        get :availabilities
        get :availability_email
        get :player_request_email
        get :lineup_email
      end
      collection do
        get :import
        post :perform_import
      end
    end
    # TODO Delete these routes 7 days later
    resources :match_availabilities, :only => [] do
      collection do
        get :set_availability
      end
    end
    # TODO Delete these routes 7 days later
    resources :practice_sessions, :only => [] do
      collection do
        get :set_availability
      end
    end
    resources :responses, :only => [:index] do
      collection do
        get :set_availability
      end
    end
    resources :results, :only => [:index]
    resources :team_members, :only => [:index, :edit, :update, :destroy] do
      collection do
        get 'new', as: :new
        post 'create', as: :create
      end
      member do
        post 'send_welcome_email'
      end
    end
    member do
      post 'send_welcome_email'
    end
  end

  resources :practices, :only => [] do
    resources :responses, :only => [:create, :update]
    member do
      post 'notify'
    end
  end

  resources :matches, :only => [] do
    resources :responses, :only => [] do
      member do
        post :save_availability
        post :save_note
      end
    end
    member do
      post 'notify'
      post 'notify_player_request'
      post 'notify_lineup'
      get 'edit_lineup' => 'match_lineups#edit'
      get 'edit_results' => 'results#edit'
    end
  end

  resource :change_password, :only => [:edit, :update] do
    member do
      get 'send_reset'
    end
  end

  namespace :api do
    post 'postmark/inbound' => 'postmark#inbound'
    post 'postmark/bounce'  => 'postmark#bounce'
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  layout 'team'

  def index
    @team = Team.find(params[:team_id])
    @matches = @team.matches
  end

  def edit
    @match = Match.find(params[:id])
    @team = @match.team
  end
end

app/views/results/_lineup.html.erb
<p>
  Results for <%= lineup.match_type %>
  <br>
  <%= lineup.players.collect(&:name).join(' and ') %>
</p>

app/views/results/_match.html.erb
<div class="alert alert-block <%= match_result_class(match) %>">
  <strong>Match</strong>
  &mdash;
  <%= match.team_location %> on
  <%= l match.date, :format => :long %>
  <br>
  <%= simple_format match.location %>
</div>

app/views/results/edit.html.erb
<% subtitle 'Record results' %>

<%= form_for(@match, :html => { :class => 'form-inline' } ) do |f| %>
  <%= f.error_messages %>
  <%= render :partial => 'match', :object => @match %>

  <%= f.fields_for :match_lineups do |match_lineup_form| %>
    <%= render :partial => 'lineup', :object => match_lineup_form.object %>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Set 1</th>
          <th>Set 2</th>
          <th>Set 3</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <%= match_lineup_form.fields_for :match_sets do |match_set_form| %>
            <td>
              <%= match_set_form.label      :games_won,  'Won' %>
              <%= match_set_form.text_field :games_won,  :class => 'span1' %>
              <%= match_set_form.label      :games_lost, 'Lost' %>
              <%= match_set_form.text_field :games_lost, :class => 'span1' %>
            </td>
          <% end %>
        </tr>
      </tbody>
    </table>
  <% end %>

  <div class="form-actions">
    <%= f.submit 'Save results', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/results/index.html.erb
<% subtitle 'Results' %>

<% if @matches.empty? %>
  <div class="alert alert-block alert-info">
    <h4>No results available because there are no matches for this team yet.</h4>
    <%= link_to 'Add a match', new_team_match_path(@team) %> to record results.
  </div>
<% else %>
  <% @matches.each do |match| %>
    <div class="row">
      <div class="span4">
        <%= render :partial => 'match', :object => match %>
        <%= link_to 'Record results', edit_results_match_path(match), :class => 'btn' %>
      </div>
      <div class="span6">

        <% match.match_lineups.each do |lineup| %>
          <%= render :partial => 'lineup', :object => lineup %>

          <table class="table table-bordered table-condensed">
            <% if lineup.has_results? %>
              <tr class="<%= lineup.won? ? 'success' : 'danger' %>">
            <% else %>
              <tr>
            <% end %>
              <% lineup.match_sets.each do |set| %>
                <td><%= "#{set.games_won}&ndash;#{set.games_lost}".html_safe %></td>
              <% end %>
            </tr>
          </table>
        <% end %>
      </div>
    </div>
    <hr>
  <% end %>
<% end %>