config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root :to => 'home#index'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :passwords     => 'users/passwords'
  }

  get 'teams' => 'teams#index', as: :user_root

  authenticate :user, lambda { |u| u.email == "davekaro@gmail.com" || u.email == "bhandari.sudershan@gmail.com" } do
    mount Sidekiq::Web => '/sidekiq'
  end

  if Rails.env.development? || Rails.env.try_it?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
    get 'try_it_sign_in' => 'try_it#auto_sign_in'
  end

  namespace :admin do
    resources :users, :only => [:index] do
      collection do
        get :test_raven
      end
      member do
        get :become
      end
    end
  end

  resources :teams, :except => [:show] do
    resources :practices do
      member do
        get :availability_email
        get :availabilities
      end
    end
    resources :matches do
      member do
        get :availabilities
        get :availability_email
        get :player_request_email
        get :lineup_email
      end
      collection do
        get :import
        post :perform_import
      end
    end
    # TODO Delete these routes 7 days later
    resources :match_availabilities, :only => [] do
      collection do
        get :set_availability
      end
    end
    # TODO Delete these routes 7 days later
    resources :practice_sessions, :only => [] do
      collection do
        get :set_availability
      end
    end
    resources :responses, :only => [:index] do
      collection do
        get :set_availability
      end
    end
    resources :results, :only => [:index]
    resources :team_members, :only => [:index, :edit, :update, :destroy] do
      collection do
        get 'new', as: :new
        post 'create', as: :create
      end
      member do
        post 'send_welcome_email'
      end
    end
    member do
      post 'send_welcome_email'
    end
  end

  resources :practices, :only => [] do
    resources :responses, :only => [:create, :update]
    member do
      post 'notify'
    end
  end

  resources :matches, :only => [] do
    resources :responses, :only => [] do
      member do
        post :save_availability
        post :save_note
      end
    end
    member do
      post 'notify'
      post 'notify_player_request'
      post 'notify_lineup'
      get 'edit_lineup' => 'match_lineups#edit'
      get 'edit_results' => 'results#edit'
    end
  end

  resource :change_password, :only => [:edit, :update] do
    member do
      get 'send_reset'
    end
  end

  namespace :api do
    post 'postmark/inbound' => 'postmark#inbound'
    post 'postmark/bounce'  => 'postmark#bounce'
  end
end

app/models/practice.rb
class Practice < ActiveRecord::Base
  include DestroyedAt
  include DateTimeParser
  include NotifyStateMachine
  include Respondable

  validates :team, presence: true

  acts_as_tenant :team
  has_paper_trail :ignore => [:notified_state, :updated_at]

  def self.notify(name, options)
    practice = find(options.fetch(:practice_id))

    practice.team.users.each do |to|
      PracticeMailer.send("practice_#{name}", practice, to.email, options.merge(user_id: to.id)).deliver
    end
  end

  # TODO This should be deleted 7 days after deploy. It is no longer used except if people click links in email after the deploy
  def self.practice_session_from_token(token)
    practice_id, user_id, timestamp = Rails.application.message_verifier("practice-email-response").verify(token)

    if timestamp < 7.days.ago
      raise Response::ResponseTokenExpired
    end

    find(practice_id).response_for(user_id)
  end

  def available_players
    responses.includes(:user).available.order(:updated_at).collect(&:user)
  end

  def not_available_players
    responses.includes(:user).not_available.order(:updated_at).collect(&:user)
  end

  def recent_changes
    versions.last.changeset
  end
end

# == Schema Information
#
# Table name: practices
#
#  id             :integer          not null, primary key
#  date           :datetime         not null
#  comment        :text
#  team_id        :integer          default(0), not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  notified_state :string(255)
#  location       :text
#

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  layout 'team'

  def index
    @upcoming_practices = current_team.upcoming_practices
    @previous_practices = current_team.previous_practices
  end

  def show
    @practice = Practice.find(params[:id])
  end

  def new
    @practice = current_team.practices.build
    @practice.date = Time.zone.now.change(hour: 14, min: 30)
  end

  def edit
    @practice = Practice.find(params[:id])
  end

  def availability_email
    @practice = Practice.find(params[:id])

    if @practice.created? || @practice.notified_team?
      @practice_email = PracticeMailer.practice_scheduled(@practice,
                                                          current_user.email,
                                                          from:     current_user.name,
                                                          reply_to: current_user.email,
                                                          preview:  true)
    else
      @practice_email = PracticeMailer.practice_updated(@practice,
                                                        current_user.email,
                                                        from:           current_user.name,
                                                        reply_to:       current_user.email,
                                                        recent_changes: @practice.recent_changes,
                                                        preview:        true)
    end
  end

  def notify
    @practice = Practice.find(params[:id])

    if @practice.created? || @practice.notified_team?
      Practice.delay.notify(:scheduled,
                            from:        current_user.name,
                            reply_to:    current_user.email,
                            comments:    params[:comments],
                            practice_id: @practice.id)
    else
      Practice.delay.notify(:updated,
                            from:           current_user.name,
                            reply_to:       current_user.email,
                            comments:       params[:comments],
                            practice_id:    @practice.id,
                            recent_changes: @practice.recent_changes)
    end

    @practice.notified!
    redirect_to team_practices_url(@practice.team), :notice => 'Availability request email sent to team'
  end

  def create
    @practice = current_team.practices.build(permitted_params.practice)

    if @practice.save
      redirect_to team_practices_url(current_team), :notice => 'Practice created'
    else
      render :new
    end
  end

  def update
    @practice = Practice.find(params[:id])

    if @practice.update_attributes(permitted_params.practice)
      if @practice.previous_changes.present?
        if @practice.notified_team? || @practice.updated?
          flash[:notice] = "Practice updated. Send updated email now, or go #{view_context.link_to("back to practices", team_practices_url(@practice.team), :class => "alert-link")}"
          next_url = availability_email_team_practice_url(current_team, @practice)
        end

        @practice.reset_notified!
      end

      if next_url.present?
        redirect_to next_url
      else
        redirect_to team_practices_url(@practice.team), :notice => 'Practice updated'
      end
    else
      render :edit
    end
  end

  def destroy
    @practice = Practice.find(params[:id])
    @practice.destroy

    redirect_to team_practices_url(@practice.team), :notice => 'Practice deleted'
  end

  def availabilities
    @practice = Practice.find(params[:id])
  end
end

app/views/practices/_form.html.erb
<%= simple_form_for([current_team, @practice]) do |f| %>
  <%= f.error_messages %>

  <div class="row">
    <div class="col-md-3">
      <%= f.input :date_string, :label => 'What day?', :input_html => { :class => 'datepicker' } %>
      <%= f.input :time_string, :label => 'What time?', :input_html => { :class => 'timepicker' } %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :location, :input_html => { :rows => '3', :class => 'span4' }, :hint => 'include club name and address' %>
      <%= f.input :comment, :input_html => { :rows => '10', :class => 'span4' }, :hint => 'provide any additional information here' %>
    </div>
  </div>

  <%= f.submit 'Save practice', :class => 'btn btn-primary' %>
  <% if !@practice.new_record?  %>
    <%= link_to 'Delete practice',
                  team_practice_path(current_team, @practice),
                  :data => { :confirm => 'Are you sure?' },
                  :method => :delete,
                  :class => 'btn btn-danger' %>
  <% end %>
<% end %>

app/views/practices/_practice.html.erb
<% response = practice.response_for(current_user.id) %>
<% show_yes_form = response.new_record? ? true : !response.yes? %>
<% show_no_form = response.new_record? ? true : response.yes? %>
<div class="panel panel-<%= response.new_record? ? 'default' : (response.yes? ? 'success' : 'danger') %>">
  <div class="panel-heading">
    <h3 class="panel-title clearfix">
      <div class="pull-left">
        <% if show_yes_form %>
          <%= form_for [practice, response], html: { style: 'margin-bottom: 0px;' } do |f| %>
            <%= f.hidden_field :state, value: "yes" %>
            <%= hidden_field_tag :team_id, current_team.id %>
            <%= submit_tag 'I can play', :class => 'btn btn-sm btn-default' %>
          <% end %>
        <% else %>
          <button class="btn btn-sm btn-success" disabled="disabled">You can play</button>
        <% end %>
      </div>

      <div class="pull-left" style="margin-left: 15px;">
        <% if show_no_form %>
          <%= form_for [practice, response], html: { style: 'margin-bottom: 0px;' } do |f| %>
            <%= f.hidden_field :state, value: "no" %>
            <%= hidden_field_tag :team_id, current_team.id %>
            <%= submit_tag "I can't play", :class => 'btn btn-sm btn-default' %>
          <% end %>
        <% else %>
          <button class="btn btn-sm btn-danger" disabled="disabled">You can't play</button>
        <% end %>
      </div>

      <div class="pull-right">
        <%= link_to 'Edit practice', edit_team_practice_path(current_team, practice), :class => 'btn btn-sm btn-default' %>
      </div>
    </h3>
  </div>
  <div class="panel-body">
    <%= render partial: 'shared/practice_details', locals: { practice: practice } %>
    <div class="row">
      <div class="col-md-5">
        <div class="row">
          <div class="col-md-3">
            <label>Availability:</label>
          </div>
          <div class="col-md-9">
            <p>
              <%= link_to availability_email_team_practice_path(current_team, practice) do %>
                <span class="glyphicon glyphicon-envelope"></span>
                Preview and send availability email
              <% end %>
            </p>
            <p>
              <%= link_to "Who can play?", availabilities_team_practice_path(current_team, practice) %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/practices/_practice_confirmations.html.erb
<div class="panel panel-<%= availability_label(status) %>">
  <div class="panel-heading clearfix">
      <h3 class="panel-title pull-left">
        <%= status %>
        <span class="badge"><%= players.size %></span>
      </h3>
  </div>
  <% if players.size > 0 %>
    <div class="list-group <%= status.parameterize %>">
      <% players.each do |player| %>
        <div class="list-group-item">
          <%= player.name %>
          (<%= player.email %>)
          <%= "- #{player.phone_number}" if player.phone_number.present? %>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="panel-body">
      No players in this group
    </div>
  <% end %>
</div>

app/views/practices/availabilities.html.erb
<% subtitle 'Review practice availability' %>

<div class="alert alert-info">
  The players are shown in the order of their response time. The player responded first will be the first in each group below.
</div>
<div class="row">
  <div class="col-md-8">
    <%= render :partial => "practice_confirmations", 
        locals: { status: 'yes', players: @practice.available_players, practice: @practice } %>
  </div>
  <div class="col-md-8">
    <%= render :partial => "practice_confirmations", 
        locals: { status: 'no', players: @practice.not_available_players, practice: @practice } %>
  </div>
</div>

app/views/practices/availability_email.html.erb
<% subtitle 'Preview and send availability request' %>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= render partial: 'shared/mailer_preview_details', locals: { subject: @practice_email.subject } %>
  </div>
  <div class="panel-body">
    <%= raw @practice_email.body %>
  </div>
</div>

<%= form_tag notify_practice_path(@practice, team_id: current_team.id), method: :post do %>
  <div class="form-group">
    <div class="row">
      <div class="col-md-8">
        <textarea placeholder="add extra comments" class="form-control" name="comments"></textarea>
        <p class="help-block">Extra comments will be included in the email above "Thanks!"</p>
      </div>
    </div>
  </div>

  <%= submit_tag 'Email team', :class => 'btn btn-primary' %>
  <% if @practice.notified_team? %>
    <span class="text-warning">
      The practice has not changed since this email was last sent
    </div>
  <% end %>
<% end %>

app/views/practices/edit.html.erb
<% subtitle 'Edit practice' %>

<%= render 'form' %>

app/views/practices/index.html.erb
<% subtitle 'Practices' %>

<% if @upcoming_practices.empty? && @previous_practices.empty? %>
  <div class="alert alert-info">
    <h4>No practices for this team yet.</h4>
    <%= link_to 'Add a practice', new_team_practice_path(current_team), :class => "alert-link" %> to get playing.
  </div>
  <p>
    <%= link_to 'Add a practice', new_team_practice_path(current_team), :class => 'btn btn-default' %>
  </p>
<% else %>
  <p>
    <%= link_to 'Add a practice', new_team_practice_path(current_team), :class => 'btn btn-default' %>
  </p>
  <% if @upcoming_practices.present? %>
    <%= render @upcoming_practices %>
  <% else %>
    <div class="alert alert-info">
      No upcoming practices
    </div>
  <% end %>
  <% if @previous_practices.present? %>
    <h3>Previous Practices</h3>
    <%= render @previous_practices %>
  <% end %>
<% end %>

app/views/practices/new.html.erb
<% subtitle 'Schedule a practice' %>

<%= render 'form' %>

app/views/practices/show.html.erb
<%= render @practice %>