config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root :to => 'home#index'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :passwords     => 'users/passwords'
  }

  get 'teams' => 'teams#index', as: :user_root

  authenticate :user, lambda { |u| u.email == "davekaro@gmail.com" || u.email == "bhandari.sudershan@gmail.com" } do
    mount Sidekiq::Web => '/sidekiq'
  end

  if Rails.env.development? || Rails.env.try_it?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
    get 'try_it_sign_in' => 'try_it#auto_sign_in'
  end

  namespace :admin do
    resources :users, :only => [:index] do
      collection do
        get :test_raven
      end
      member do
        get :become
      end
    end
  end

  resources :teams, :except => [:show] do
    resources :practices do
      member do
        get :availability_email
        get :availabilities
      end
    end
    resources :matches do
      member do
        get :availabilities
        get :availability_email
        get :player_request_email
        get :lineup_email
      end
      collection do
        get :import
        post :perform_import
      end
    end
    # TODO Delete these routes 7 days later
    resources :match_availabilities, :only => [] do
      collection do
        get :set_availability
      end
    end
    # TODO Delete these routes 7 days later
    resources :practice_sessions, :only => [] do
      collection do
        get :set_availability
      end
    end
    resources :responses, :only => [:index] do
      collection do
        get :set_availability
      end
    end
    resources :results, :only => [:index]
    resources :team_members, :only => [:index, :edit, :update, :destroy] do
      collection do
        get 'new', as: :new
        post 'create', as: :create
      end
      member do
        post 'send_welcome_email'
      end
    end
    member do
      post 'send_welcome_email'
    end
  end

  resources :practices, :only => [] do
    resources :responses, :only => [:create, :update]
    member do
      post 'notify'
    end
  end

  resources :matches, :only => [] do
    resources :responses, :only => [] do
      member do
        post :save_availability
        post :save_note
      end
    end
    member do
      post 'notify'
      post 'notify_player_request'
      post 'notify_lineup'
      get 'edit_lineup' => 'match_lineups#edit'
      get 'edit_results' => 'results#edit'
    end
  end

  resource :change_password, :only => [:edit, :update] do
    member do
      get 'send_reset'
    end
  end

  namespace :api do
    post 'postmark/inbound' => 'postmark#inbound'
    post 'postmark/bounce'  => 'postmark#bounce'
  end
end

app/models/match.rb
class Match < ActiveRecord::Base
  NOTIFIED_LINEUP_STATES = %w[lineup_created lineup_updated notified_team_lineup]

  include DestroyedAt
  include DateTimeParser
  include NotifyStateMachine
  include Respondable

  has_many :match_lineups, -> { order(:ordinal) }, :dependent => :destroy

  validates :team, presence: true

  accepts_nested_attributes_for :match_lineups

  after_create :setup_match_lineups
  after_create :setup_match_responses

  delegate :lineup_created?, :lineup_updated?, :notified_team_lineup?, :to => :notified_team_lineup_state

  acts_as_tenant :team
  has_paper_trail :ignore => [:notified_state, :notified_lineup_state, :updated_at]

  def self.notify(name, options)
    match = find(options.fetch(:match_id))

    if options[:user_ids]
      send_to = match.team.users.select { |u| options[:user_ids].include?(u.id) }
    else
      send_to = match.team.users
    end

    send_to.each do |to|
      MatchMailer.send("match_#{name}", match, to.email, options.merge(user_id: to.id)).deliver
    end
  end

  # TODO This should be deleted 7 days after deploy. It is no longer used except if people click links in email after the deploy
  def self.match_availability_from_token(token)
    match_id, user_id, timestamp = Rails.application.message_verifier("match-email-response").verify(token)

    if timestamp < 7.days.ago
      raise Response::ResponseTokenExpired
    end

    find(match_id).response_for(user_id)
  end

  def team_location
    home_team? ? 'Home' : 'Away'
  end

  def available_players
    player_status(responses.includes(:user).available)
  end

  def maybe_available_players
    player_status(responses.includes(:user).maybe_available)
  end

  def not_available_players
    player_status(responses.includes(:user).not_available)
  end

  def no_response_players
    player_status(responses.includes(:user).no_response)
  end

  def player_status(responses)
    responses.map do |response|
      if response.note.blank?
        [response.user.name, response.user.id]
      else
        ["#{response.user.name} - #{response.note}", response.user.id]
      end
    end
  end

  def players_status
    @players_status ||= {
      "Yes"         => available_players,
      "Maybe"       => maybe_available_players,
      "No"          => not_available_players,
      "No Response" => no_response_players
    }
  end

  def recent_changes
    versions.last.changeset
  end

  def lineup_changed?
    match_lineups.flat_map(&:match_players).map(&:previous_changes).reject { |change| change.blank? }.present?
  end

  def notified_team_lineup_state
    (notified_lineup_state || NOTIFIED_LINEUP_STATES.first).inquiry
  end

  def reset_notified_lineup!
    update_attributes!(:notified_lineup_state => 'lineup_updated') if notified_team_lineup?
  end

  def notified_lineup!
    update_attributes!(:notified_lineup_state => 'notified_team_lineup') if lineup_created? || lineup_updated?
  end

  def has_results?
    match_lineups.collect { |l| l.has_results? }.any?
  end

  def won?
    matches_won > matches_lost
  end

  def matches_won
    result[true]
  end

  def matches_lost
    result[false]
  end

  private

  def setup_match_lineups
    ordinal = 0
    1.upto(team.singles_matches) do |singles_match|
      lineup = match_lineups.create :match_type => "##{singles_match} Singles", :ordinal => ordinal
      lineup.match_players.create
      1.upto(3) { |i| lineup.match_sets.create(:ordinal => i) }
      ordinal += 1
    end

    1.upto(team.doubles_matches) do |doubles_match|
      lineup = match_lineups.create :match_type => "##{doubles_match} Doubles", :ordinal => ordinal
      2.times { lineup.match_players.create }
      1.upto(3) { |i| lineup.match_sets.create(:ordinal => i) }
      ordinal += 1
    end
  end

  def setup_match_responses
    ActsAsTenant.with_tenant(team) do
      team.team_members.each do |team_member|
        responses.create!(user_id: team_member.user_id)
      end
    end
  end

  def result
    @result ||= match_lineups.collect { |l| l.won? }.inject(Hash.new(0)) { |h,i| h[i] += 1; h }
  end
end

# TODO
# Split Format (enable second time option - for double?)

# == Schema Information
#
# Table name: matches
#
#  id             :integer          not null, primary key
#  date           :datetime         not null
#  location       :text             default(""), not null
#  team_id        :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  notified_state :string(255)
#  home_team      :boolean          default(TRUE)
#  comment        :text
#

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  layout 'team'

  def index
    @matches = current_team.matches
  end

  def show
    @match = Match.find(params[:id])
  end

  def new
    @match = current_team.matches.build
    @match.date = Time.zone.now.change(hour: 14, min: 30)
  end

  def edit
    @match = Match.find(params[:id])
    authorize current_team
  end

  def availability_email
    @match = Match.find(params[:id])
    authorize current_team, :update?

    if @match.created? || @match.notified_team?
      @match_email = MatchMailer.match_scheduled(@match,
                                                 current_user.email,
                                                 from:     current_user.name,
                                                 reply_to: current_user.email,
                                                 preview:  true)
    else
      @match_email = MatchMailer.match_updated(@match,
                                               current_user.email,
                                               from:           current_user.name,
                                               reply_to:       current_user.email,
                                               recent_changes: @match.recent_changes,
                                               preview:        true)
    end
  end

  def availabilities
    @match = Match.find(params[:id])
  end

  def player_request_email
    @match = Match.find(params[:id])
    authorize current_team, :update?

    @users = current_team.users.where(id: params[:user_ids].split(",").map(&:to_i))
    @player_request_email = MatchMailer.match_player_request(@match,
                                                             current_user.email,
                                                             from:     current_user.name,
                                                             reply_to: current_user.email,
                                                             preview:  true)
  end

  def lineup_email
    @match = Match.find(params[:id])
    authorize current_team, :update?

    if @match.lineup_created? || @match.notified_team_lineup?
      @match_lineup_email = MatchMailer.match_lineup_set(@match,
                                                         current_user.email,
                                                         from:     current_user.name,
                                                         reply_to: current_user.email)
    else
      @match_lineup_email = MatchMailer.match_lineup_updated(@match,
                                                             current_user.email,
                                                             from:           current_user.name,
                                                             reply_to:       current_user.email)
    end
  end

  def notify
    @match = Match.find(params[:id])
    authorize current_team, :update?

    if @match.created? || @match.notified_team?
      Match.delay.notify(:scheduled,
                         from:     current_user.name,
                         reply_to: current_user.email,
                         comments: params[:comments],
                         match_id: @match.id)
    else
      Match.delay.notify(:updated,
                         from:           current_user.name,
                         reply_to:       current_user.email,
                         comments:       params[:comments],
                         match_id:       @match.id,
                         recent_changes: @match.recent_changes)
    end

    @match.notified!
    redirect_to team_matches_url(@match.team), :notice => 'Availability request email sent to team'
  end

  def notify_player_request
    @match = Match.find(params[:id])
    authorize current_team, :update?

    @users = current_team.users.where(id: params[:user_ids].map(&:to_i))
    Match.delay.notify(:player_request,
                       from:     current_user.name,
                       reply_to: current_user.email,
                       comments: params[:comments],
                       match_id: @match.id,
                       user_ids: @users.pluck(:id))

    redirect_to team_matches_url(@match.team), :notice => 'Player request email sent'
  end

  def notify_lineup
    @match = Match.find(params[:id])
    authorize current_team, :update?

    if @match.lineup_created? || @match.notified_team_lineup?
      Match.delay.notify(:lineup_set,
                         from:     current_user.name,
                         reply_to: current_user.email,
                         comments: params[:comments],
                         match_id: @match.id)
    else
      Match.delay.notify(:lineup_updated,
                         from:           current_user.name,
                         reply_to:       current_user.email,
                         comments:       params[:comments],
                         match_id:       @match.id)
    end

    @match.notified_lineup!
    redirect_to team_matches_url(@match.team), :notice => 'Lineup email sent to team'
  end

  def import
    authorize current_team
  end

  def perform_import
    authorize current_team, :import?

    scraper = UstaScraper.new(params[:team_number], params[:year])
    importer = UstaImporter.new(current_team.id, scraper.matches)
    importer.import

    redirect_to team_matches_url(current_team), :notice => 'Matches imported from USTA'
  rescue => e
    Rollbar.report_exception(e, rollbar_request_data, rollbar_person_data)
    redirect_to team_matches_url(current_team), flash: { error: "Sorry, an error occurred during import. We have been notified and will let you know once it's fixed" }
  end

  def create
    @match = current_team.matches.build(permitted_params.match)
    authorize current_team

    if @match.save
      redirect_to team_matches_url(current_team), :notice => 'Match created'
    else
      render :new
    end
  end

  def update
    @match = Match.find(params[:id])
    authorize current_team

    if @match.update_attributes(permitted_params.match)
      if @match.previous_changes.present?
        if @match.notified_team? || @match.updated?
          flash[:notice] = "Match updated. Send updated email now, or go #{view_context.link_to("back to matches", team_matches_url(@match.team), :class => "alert-link")}"
          next_url = availability_email_team_match_url(current_team, @match)
        end

        @match.reset_notified!
      elsif @match.lineup_changed?
        if @match.notified_team_lineup? || @match.lineup_updated?
          flash[:notice] = "Lineup updated. Send updated email now, or go #{view_context.link_to("back to matches", team_matches_url(@match.team), :class => "alert-link")}"
          next_url = lineup_email_team_match_url(current_team, @match)
        end

        @match.reset_notified_lineup!
      end

      if next_url.present?
        redirect_to next_url
      else
        redirect_to team_matches_url(@match.team), :notice => 'Match updated'
      end
    else
      render :edit
    end
  end

  def destroy
    @match = Match.find(params[:id])
    authorize current_team
    @match.destroy

    redirect_to team_matches_url(@match.team), :notice => 'Match deleted'
  end
end

app/views/matches/_availability_help.html.erb
Click the
<a href="#" class="btn btn-xs btn-default disabled">
  <span class="glyphicon glyphicon-check"></span>
  All
</a>
<a href="#" class="btn btn-xs btn-default disabled">
  <span class="glyphicon glyphicon-unchecked"></span>
  None
</a>
buttons or click individual players to select/deselect them.

app/views/matches/_form.html.erb
<%= simple_form_for([current_team, @match]) do |f| %>
  <%= f.error_messages %>

  <div class="row">
    <div class="col-md-3">
      <%= f.input :date_string, :label => 'What day?', :input_html => { :class => 'datepicker' } %>
      <%= f.input :time_string, :label => 'What time?', :input_html => { :class => 'timepicker' } %>
      <%= f.input :home_team, :hint => 'uncheck if your team is the Away team' %>
      <%= f.input :opponent, :hint => 'include opponent name' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :location, :input_html => { :rows => '3',  :class => 'span4' }, :hint => 'include club name and address' %>
      <%= f.input :comment, :input_html => { :rows => '10', :class => 'span4' }, :hint => 'provide any additional information here' %>
    </div>
  </div>

  <%= f.submit 'Save match', :class => 'btn btn-primary' %>
  <% if !@match.new_record?  %>
    <%= link_to 'Delete match',
      team_match_path(current_team, @match),
      :data => { :confirm => 'Are you sure?' },
      :method => :delete,
      :class => 'btn btn-danger' %>
  <% end %>
<% end %>

app/views/matches/_match.html.erb
<% response = match.response_for(current_user.id) %>
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <h4 class="panel-title" style="display: inline-block; vertical-align: middle;">
      <a data-toggle="collapse" href="#match-<%= match.id %>">
        <span class="glyphicon glyphicon-chevron-<%= match.date.future? ? "down" : "right"%>"></span>
        <%= l match.date, :format => :long_date %>
        - <%= match.team_location %>
        <% if match.opponent.present? %>
          against <%= match.opponent %>
        <% end %>
      </a>
    </h4>

    <% if policy(current_team).captain? %>
      <%= link_to 'Edit match', edit_team_match_path(current_team, match), :class => 'pull-right btn btn-sm btn-default' %>
    <% end %>
  </div>
  <div class="panel-collapse collapse<%= " in" if match.date.future? %>" id="match-<%= match.id %>">
    <div class="panel-body">
      <div class="alert alert-<%= availability_label(response.state) %>">
        Can you play?
        <div class="btn-group btn-group-sm">
          <%= link_to "Yes",
            save_availability_match_response_path(match, response, team_id: current_team.id, state: 'yes'),
            data: { label: 'success' },
            remote: true,
            method: :post,
            class: "availability btn btn-#{response.yes? ? 'success disabled' : 'default'}" %>

          <%= link_to "Maybe",
            save_availability_match_response_path(match, response, team_id: current_team.id, state: 'maybe'),
            data: { label: 'info' },
            remote: true,
            method: :post,
            class: "availability btn btn-#{response.maybe? ? 'info disabled' : 'default'}" %>

          <%= link_to "No",
            save_availability_match_response_path(match, response, team_id: current_team.id, state: 'no'),
            data: { label: 'danger' },
            remote: true,
            method: :post,
            class: "availability btn btn-#{response.no? ? 'danger disabled' : 'default'}" %>
        </div>
        <% if response.note.blank? %>
          <%= link_to "Add note (for captain)", "#", class: "note-action" %>
        <% else %>
          <span><%= response.note %></span>
          <%= link_to "Edit note", "#", class: "note-action" %>
        <% end %>
        <div class="hidden note-form form-inline btn-group">
          <div class="form-group">
            <%= text_field_tag :note, response.note, class: "note form-control input-sm", style: "width: 250px;" %>
          </div>
          <%= link_to "Save", save_note_match_response_path(match, response, team_id: current_team.id), class: "save-note" %>
        </div>
      </div>
      <% if policy(current_team).captain? %>
        <%= render partial: 'shared/match_details', locals: { match: match } %>
        <div class="row">
          <div class="col-md-5">
            <div class="row">
              <div class="col-md-3">
                <label>Availability:</label>
              </div>
              <div class="col-md-9">
                <p>
                  <%= link_to availability_email_team_match_path(current_team, match) do %>
                    <span class="glyphicon glyphicon-envelope"></span>
                    Preview and send availability email
                  <% end %>
                </p>
                <p>
                  <%= link_to "Who can play?", availabilities_team_match_path(current_team, match) %>
                </p>
              </div>
            </div>
          </div>
          <div class="col-md-7">
            <div class="row">
              <div class="col-md-3 col-lg-2">
                <label>Lineup:</label>
              </div>
              <div class="col-md-9 col-lg-10">
                <p><%= link_to 'Set the lineup', edit_lineup_match_path(match, team_id: current_team.id) %></p>
                <p>
                  <%= link_to lineup_email_team_match_path(current_team, match) do %>
                    <span class="glyphicon glyphicon-envelope"></span>
                    Preview and send lineup email
                  <% end %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <%= render partial: 'shared/match_details', locals: { match: match } %>
      <% end %>
    </div>
  </div>
</div>

app/views/matches/_matches.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="pull-right">
      <a href="#" class="expand-all">
        <span class="glyphicon glyphicon-chevron-down"></span>
        Expand all
      </a>
      <a href="#" class="collapse-all">
        <span class="glyphicon glyphicon-chevron-right"></span>
        Collapse all
      </a>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="panel-group">
      <%= render matches %>
    </div>
  </div>
</div>
<%= render partial: "match_javascript" %>

app/views/matches/availabilities.html.erb
<% subtitle 'Review team availability' %>

<div class="row">
  <div class="col-md-8">
    <% @match.players_status.each do |status, players| %>
      <div class="panel panel-<%= availability_label(status) %>">
        <div class="panel-heading clearfix">
          <h3 class="panel-title pull-left">
            <%= status %>
            <span class="badge"><%= players.size %></span>
          </h3>
          <div class="pull-right">
            <a href="#" class="select-all btn btn-xs btn-<%= availability_label(status) %>">
              <span class="glyphicon glyphicon-check"></span>
              All
            </a>
            <a href="#" class="select-none btn btn-xs btn-<%= availability_label(status) %>">
              <span class="glyphicon glyphicon-unchecked"></span>
              None
            </a>
          </div>
        </div>
        <% if players.size > 0 %>
          <div class="list-group <%= status.parameterize %>">
            <% players.each do |player| %>
              <a href="#" class="list-group-item" data-user-id="<%= player.last %>">
                <span class="glyphicon glyphicon-unchecked"></span>
                <%= player.first %>
              </a>
            <% end %>
          </div>
        <% else %>
          <div class="panel-body">
            No players in this group
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="panel panel-default">
      <div class="panel-heading">
        Email selected players
        <span class="badge selected-players">0</span>
      </div>
      <div class="panel-body">
        <%= link_to player_request_email_team_match_path(current_team, @match), class: "player-request-email player-request-email-right btn btn-primary" do %>
          <span class="glyphicon glyphicon-envelope"></span>
          Preview and send player request email
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="alert alert-info">
      <h4>Need more players?</h4>
      Click the
      <a href="#" class="btn btn-xs btn-info disabled">
        <span class="glyphicon glyphicon-check"></span>
        All
      </a>
      <a href="#" class="btn btn-xs btn-info disabled">
        <span class="glyphicon glyphicon-unchecked"></span>
        None
      </a>
      buttons or click individual players to select/deselect them.
      <hr>
      Once players are selected,
      <%= link_to player_request_email_team_match_path(current_team, @match), class: "player-request-email player-request-email-bottom" do %>
        <span class="glyphicon glyphicon-envelope"></span>
        Preview and send player request email
      <% end %>
    </div>
  </div>
</div>

<script>
  function toggleSelectedPlayer(items, selected) {
    $.each(items, function(index, item) {
      if (selected) {
        $(item).addClass('list-group-item-info');
        $(item).children('span').removeClass('glyphicon-unchecked').addClass('glyphicon-check');
      } else {
        $(item).removeClass('list-group-item-info');
        $(item).children('span').removeClass('glyphicon-check').addClass('glyphicon-unchecked');
      }
    });
    $('.selected-players').text(selectedUserIds().length);
    if (selectedUserIds().length > 0) {
      $('.player-request-email').popover('hide');
    }
  }

  function selectedUserIds() {
    return $.map($('.list-group-item-info'), function(user) {
      return $(user).data('user-id');
    });
  }

  $(function() {
    $('.player-request-email-right').popover({
      html: true,
      trigger: 'manual',
      placement: 'right',
      title: 'No players are selected',
      content: "<%= j render partial: 'availability_help' %>"
    });

    $('.player-request-email-bottom').popover({
      html: true,
      trigger: 'manual',
      placement: 'bottom',
      title: 'No players are selected',
      content: "<%= j render partial: 'availability_help' %>"
    });

    $('.player-request-email').on('click', function(e) {
      e.preventDefault();

      if (selectedUserIds().length > 0) {
        window.location = $(this).prop('href') + "?user_ids=" + selectedUserIds().toString();
      } else {
        $(this).popover('show');
      }
    });

    $('.select-all').on('click', function(e) {
      e.preventDefault();
      var items = $(this).closest('.panel').find('.list-group-item');
      toggleSelectedPlayer(items, true);
    });

    $('.select-none').on('click', function(e) {
      e.preventDefault();
      var items = $(this).closest('.panel').find('.list-group-item');
      toggleSelectedPlayer(items, false);
    });

    $('.list-group').on('click', '.list-group-item', function(e) {
      e.preventDefault();
      var currentlySelected = $(this).hasClass('list-group-item-info');
      toggleSelectedPlayer($(this), !currentlySelected);
    });
  });
</script>

app/views/matches/availability_email.html.erb
<% subtitle 'Preview and send availability request' %>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= render partial: 'shared/mailer_preview_details', locals: { subject: @match_email.subject } %>
  </div>
  <div class="panel-body">
    <%= raw @match_email.body %>
  </div>
</div>

<%= form_tag notify_match_path(@match, team_id: current_team.id), method: :post do %>
  <div class="form-group">
    <div class="row">
      <div class="col-md-8">
        <textarea placeholder="add extra comments" class="form-control" name="comments"></textarea>
        <p class="help-block">Extra comments will be included in the email above "Thanks!"</p>
      </div>
    </div>
  </div>

  <%= submit_tag 'Email team', :class => 'btn btn-primary' %>
  <% if @match.notified_team? %>
    <span class="text-warning">
      The match has not changed since this email was last sent
    </span>
  <% end %>
<% end %>

app/views/matches/edit.html.erb
<% subtitle 'Edit match' %>

<%= render 'form' %>

app/views/matches/import.html.erb
<% subtitle 'Import Matches' %>

<div class="alert alert-info">
  <h4>Save time by importing matches from USTA</h4>
  <p>All we need is your team number. We won't save the team number or use it for anything else except this one time to grab the schedule from the USTA website.</p>
  <p>If you have a match on the same day, it will be skipped.</p>
</div>


<%= form_tag perform_import_team_matches_path(current_team) do %>
  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <%= label_tag :team_number %>
        <%= text_field_tag :team_number, '', class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :year %>
        <%= text_field_tag :year, Time.now.year, class: "form-control" %>
      </div>
    </div>
  </div>
  <%= submit_tag "Import", class: "btn btn-primary" %>
<% end %>

app/views/matches/index.html.erb
<% subtitle 'Matches' %>

<% if @matches.present? %>
  <p>
    <% if policy(current_team).captain? %>
      <%= link_to 'Add a match', new_team_match_path(current_team), :class => 'btn btn-default' %>
      <%= link_to 'Import matches', import_team_matches_path(current_team), :class => "btn btn-default" %>
    <% end %>
    <%= link_to 'See who can play when', team_responses_path(current_team), :class => 'btn btn-default' %>
  </p>
  <%= render :partial => "matches", :object => @matches %>
<% else %>
  <% if policy(current_team).captain? %>
    <div class="alert alert-info">
      <h4>No matches for this team yet</h4>
      <%= link_to 'Add a match', new_team_match_path(current_team), :class => "alert-link" %>
      or
      <%= link_to 'import matches (USTA only)', import_team_matches_path(current_team), :class => "alert-link" %> to get playing.
    </div>
    <p>
      <%= link_to 'Add a match', new_team_match_path(current_team), :class => 'btn btn-default' %>
      <%= link_to 'Import matches', import_team_matches_path(current_team), :class => "btn btn-default" %>
    </p>
  <% else %>
    <div class="alert alert-info">
      <h4>The captain has not added any matches yet</h4>
    </div>
  <% end %>
<% end %>

app/views/matches/lineup_email.html.erb
<% subtitle 'Preview and send lineup' %>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= render partial: 'shared/mailer_preview_details', locals: { subject: @match_lineup_email.subject } %>
  </div>
  <div class="panel-body">
    <%= raw @match_lineup_email.body %>
  </div>
</div>

<%= form_tag notify_lineup_match_path(@match, team_id: current_team.id), method: :post do %>
  <div class="form-group">
    <div class="row">
      <div class="col-md-8">
        <textarea placeholder="add extra comments" class="form-control" name="comments"></textarea>
        <p class="help-block">Extra comments will be included in the email above "Thanks!"</p>
      </div>
    </div>
  </div>

  <%= submit_tag 'Email team', :class => 'btn btn-primary' %>
  <% if @match.notified_team_lineup? %>
    <span class="text-warning">
      The lineup has not changed since this email was last sent
    </span>
  <% end %>
<% end %>

app/views/matches/new.html.erb
<% subtitle 'Schedule a match' %>

<%= render 'form' %>

app/views/matches/player_request_email.html.erb
<% subtitle 'Preview and send player request email' %>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= render partial: 'shared/mailer_preview_details', locals: { to: @users.collect(&:name).join(", "), subject: @player_request_email.subject } %>
  </div>
  <div class="panel-body">
    <%= raw @player_request_email.body %>
  </div>
</div>

<%= form_tag notify_player_request_match_path(@match, team_id: current_team.id), method: :post do %>
  <div class="form-group">
    <div class="row">
      <div class="col-md-8">
        <textarea placeholder="add extra comments" class="form-control" name="comments"></textarea>
        <p class="help-block">Extra comments will be included in the email above "Thanks!"</p>
      </div>
    </div>
  </div>

  <% @users.each do |user| %>
    <%= hidden_field_tag 'user_ids[]', user.id %>
  <% end %>

  <%= submit_tag 'Email player request', :class => 'btn btn-primary' %>
<% end %>

app/views/matches/show.html.erb
<%= render @match %>
<%= render partial: "match_javascript" %>